<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Rahul07" name="WesternUnion_NZsitePageClass.TrackTransferClass" tests="11" failures="1" timestamp="28 Aug 2018 16:52:23 GMT" time="97.128" errors="0">
  <testcase name="TrackTransferModule" time="62.059" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="EnterWrongMTCNNumber" time="0.601" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="ErrorMessageInString" time="5.836" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="ErrorMessageInNumber" time="0.029" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="EnterCorrectMTCNnumber" time="6.748" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="StatusOfValidMTCNnumber" time="3.024" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="TrackNewTransfer" time="2.477" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="DontHaveMTCNNumber" time="6.541" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
  <testcase name="SearchMTCNWithoutMTCNNumber" time="0.005" classname="WesternUnion_NZsitePageClass.TrackTransferClass">
    <skipped/>
  </testcase> <!-- SearchMTCNWithoutMTCNNumber -->
  <testcase name="FailingThisMethod" time="0.004" classname="WesternUnion_NZsitePageClass.TrackTransferClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at WesternUnion_NZsitePageClass.TrackTransferClass.FailingThisMethod(TrackTransferClass.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FailingThisMethod -->
  <testcase name="SenderPhoneNumberModule" time="9.804" classname="WesternUnion_NZsitePageClass.TrackTransferClass"/>
</testsuite> <!-- WesternUnion_NZsitePageClass.TrackTransferClass -->
